config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'
  get 'home/about'
  get 'home/contact'
  get 'home/mission'
  get 'home/news'
  get 'home/news_post/:id', to:"home#news_post", as:"home_news_post"
  get 'home/details/:id', to:"home#details", as:"home_details_post"
  get 'home/astroTg'
  get 'home/astroVn'
  get 'home/question'
  get 'home/discovery'
  get 'home/knowledge'
  resources :images, :only=>[:index, :new, :create, :destroy]
  get "images/index"
  get 'images/new'
  get 'images/create'
  get 'images/destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :news
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :element_id
  validates_presence_of :description
  belongs_to :element
  has_many :images
end

app/models/element.rb
class Element < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :system_id
  belongs_to :system
  has_many:missions
  has_many:details

end

app/models/image.rb
class Image < ActiveRecord::Base
  validates_presence_of :image_path
  validates_presence_of :attachment

  belongs_to:news
  belongs_to:mission
  belongs_to:detail
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :image_path, presence:true # Make sure the owner's name is present.

end

app/models/lienket.rb
class Lienket < ActiveRecord::Base
  belongs_to:mission
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :element_id
  validates_presence_of :status_id
  belongs_to :element
  has_many :images
  has_many :lienkets
  belongs_to :status
end

app/models/news.rb
class News < ActiveRecord::Base
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :category_id
  belongs_to :category
  has_many :images

end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :missions
end

app/models/system.rb
class System < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :elements
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #devise :database_authenticatable, :registerable, :confirmable, :recoverable, stretches: 20
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @title="Trang Chủ"
    @planet=Detail.limit(8)
    @news=News.order("created_at DESC").limit(4)
    @mission=Mission.order("created_at DESC").limit(1)
  end
  def contact
    @title="Liên Hệ"
  end
  def about
    @title="Giới Thiệu"
  end
  def news_post
    @post=News.find(params[:id])
    @title=@post.title
    @news=News.order("created_at DESC").limit(3)
  end
  def details
    @details = Detail.where(:element_id=>params[:id]).order("id DESC").limit(1)
    @news=News.order("created_at DESC").limit(3)
    @title=@details[0].name
  end
  def mission
    @title="Nhiệm vụ thăm dò́"
    @mission=Mission.all
  end
  def astroTg
    @title="Thiên văn thế giớí"
    @post=News.where(:category=>"2")
    @news=News.order("created_at DESC").limit(3)
  end
  def astroVn
    @title="Thiên văn Việt Naḿ"
    @post=News.where(:category=>"1")
    @news=News.order("created_at DESC").limit(3)
  end
  def news
    @title="Tin tức"
  end
  def question
    @title="Câu Hỏi Thường Gặp"
  end
  def discovery
    @title="Khám Phá"
  end
  def knowledge
    @title="Kiến Thức"
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # def index
  #   @images = Image.all
  # end
  #
  # def new
  #   @image = Image.new
  # end
  #
  # def create
  #   @image = Image.new(image_params)
  #
  #   if @image.save
  #     redirect_to images_path, notice:"The image #{@image.image_path} has been uploaded."
  #   else
  #     render "new"
  #   end
  # end
  #
  # def destroy
  #   @image = Image.find(params[:id])
  #   @image.destroy
  #   redirect_to images_path, notice:"The image #{@image.image_path} has been deleted."
  # end
  #
  #
  # def image_params
  #   params.require(:image).permit(:image_path, :attachment)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/discovery.html.erb
<!-- Content
======================================= -->

<div class="page_title2">
  <div class="container">

    <div class="title"><h1>Khám phá thiên văn</h1></div>

    <div class="pagenation">&nbsp;<a href="index.html">Trang chủ</a> <i>/</i> Khám phá</div>

  </div>
</div><!-- end page title -->

<div class="clearfix"></div>

<div class="features_sec8">
  <div class="container">

    <h2 class="section_title_drakgray lessmar">Khám phá</h2>
    <br>
    <div class="content_box">

      <div class="left">

        <h3><img src="<%= image_path("icon/icon-8.png") %>" alt="" /> Quan sát thiên văn</h3>

        <ul>
          <li><a href="#">Tiêu điểm quan sát</a></li>
          <li><a href="#">Dụng cụ quan sát</a></li>
          <li><a href="#">Kĩ năng quan sát</a></li>
        </ul>

      </div><!-- end section -->

      <div class="vline"></div>


      <div class="center">

        <h3><img src="<%= image_path('icon/icon-9.png') %>" alt="" /> Vũ trụ học & Vật lý thiên văn</h3>

        <ul>
          <li><a href="#">Vật lý thiên văn & Hạt nhân</a></li>
          <li><a href="#">Vật chất tối & Năng lượng tối</a></li>
          <li><a href="#">Sự hình thành vũ trụ</a></li>
        </ul>

      </div><!-- end section -->

      <div class="vline"></div>

      <div class="right">

        <h3><img src="<%= image_path('icon/icon-10.png') %>" alt="" /> Công nghệ khám phá vũ trụ</h3>

        <ul>
          <li><a href="#">Kính thiên văn</a></li>
          <li><a href="#">Tàu thăm dò</a></li>
          <li><a href="#">Tên lửa vũ trụ</a></li>
          <li><a href="#">Vệ tinh nhân tạo</a></li>
        </ul>

      </div><!-- end section -->

    </div>

  </div>
</div><!-- end features section8 -->

<div class="clearfix margin_top4"></div>

app/views/home/index.html.erb
<!-- Slider  -->
<div class="container_full">
  <div class="tp-banner-container">
    <div class="tp-banner">
      <ul>
        <!-- SLIDE 1 -->
        <li data-transition="curtain-1" data-slotamount="7" data-masterspeed="1000">
          <img src="<%= image_path("sliders/1.jpg") %>" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
        </li>

        <!-- SLIDE 2 -->
        <li data-transition="boxslide" data-slotamount="7" data-masterspeed="1000">
          <img src="<%= image_path("sliders/2.jpg") %>" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
        </li>

        <!-- SLIDE 3 -->
        <li data-transition="curtain-2" data-slotamount="7" data-masterspeed="1000">
          <img src="<%= image_path("sliders/3.jpg") %>" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
        </li>

        <!-- SLIDE 4 -->
        <li data-transition="boxslide" data-slotamount="7" data-masterspeed="1000">
          <img src="<%= image_path("sliders/4.jpg") %>" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
        </li>

        <!-- SLIDE 5 -->
        <li data-transition="curtain-1" data-slotamount="7" data-masterspeed="1000">
          <img src="<%= image_path("sliders/5.jpg") %>" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">
        </li>

        <!-- SLIDE 6 -->
        <li data-transition="boxslide" data-slotamount="7" data-masterspeed="1000">
          <img src="<%= image_path("sliders/6.jpg") %>" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat">

        </li>
      </ul>
    </div>
  </div>
</div> <!-- end slider -->


<div class="clearfix"></div>

<div class="features_sec1">
  <div class="container">
    <h2 class="section_title_drakgray">Hệ Mặt Trời</h2>

    <% @planet.each do |item| %>
        <div class="one_fourth">
          <img src="<%= item.images[0].attachment_url %>" alt="Side Logo"/>

          <div class="clearfix"></div>

          <h3 class="nocaps"><%= link_to item.element.name, home_details_post_path(item.element_id) %></h3>

          <p><%= item.description %></p>
          <br/>

        </div>
    <% end %>

  </div>
</div><!-- end features section1 -->

<div class="clearfix"></div>

<div class="features_sec9">
  <div class="container">

    <h2 class="section_title_white"><strong>Thư viện</strong></h2>

    <div class="one_fourth">
      <div class="box">
        <a href="#">
          <div class="image">
            <div>
              <i class="fa fa-camera"></i>
              <h4>Hình ảnh</h4>
            </div>

          </div>
          <div class="text">
            <div><h4>Hình ảnh</h4> Tổng hợp những hình ảnh thiên văn ấn tượng, mới nhất...</div>
          </div>
        </a>
      </div>

    </div>
    <!-- end section -->

    <div class="one_fourth">
      <div class="box">
        <a href="#">
          <div class="image">

            <div>
              <i class="fa fa-video-camera"></i>
              <h4>Video Clip</h4>
            </div>

          </div>
          <div class="text">
            <div><h4>Video Clip</h4> Tổng hợp những clip thiên văn rõ nét, sống động...</div>
          </div>
        </a>
      </div>

    </div>
    <!-- end section -->

    <div class="one_fourth">
      <div class="box">
        <a href="#">
          <div class="image">

            <div>
              <i class="fa fa-book"></i>
              <h4>Sách báo</h4>
            </div>

          </div>
          <div class="text">
            <div><h4>Sách báo</h4> Tổng hợp những link download sách báo thiên văn hay nhất...</div>
          </div>
        </a>
      </div>

    </div>
    <!-- end section -->

    <div class="one_fourth last">
      <div class="box">
        <a href="#">
          <div class="image">
            <div>
              <i class="fa fa-smile-o"></i>
              <h4>Fun facts</h4>
            </div>

          </div>
          <div class="text">
            <div><h4>Fun facts</h4> Tổng hợp những câu chuyện thiên văn thú vị, hài hước...</div>
          </div>
        </a>
      </div>

    </div>
    <!-- end section -->

  </div>
</div><!-- end features section9 -->

<div class="clearfix"></div>

<div class="features_sec27">
  <div class="container">
    <span style="text-align: center;">
      <h2 class="section_title_drakgray"><%= link_to "Tin mới", home_news_path %></h2></span>
    <% @news.each do |news_post| %>
        <div class="one_fourth">

          <ul class="blogs2">
            <li><a href="#"><img src="<%= news_post.images.first.attachment_url %>" alt="ảnh bài viết" /></a></li>
            <li><h4 class="nocaps"><%=link_to news_post.title, home_news_post_path(news_post.id), :class=>"two" %></h4></li>
            <li><i class="fa fa-clock-o"></i><%= news_post.created_at %> &nbsp;&nbsp;<i class="fa fa-user"></i>
             Admin
            </li>
          </ul>

        </div>
    <% end %>
  </div>
</div><!-- end features section27 -->

<div class="clearfix"></div>

<div class="features_sec24">
  <div class="container">

    <div class="latestnews">

      <h2 class="section_title_drakgray left">Hoạt động</h2>

      <ul class="news">
        <li class="left"><a href="#"><img src="<%= image_path("home/act1.jpg") %>" alt=""/></a></li>
        <li><h5><a href="#">Hội trại thiên văn</a></h5> <i class="fa fa-clock-o"></i> Nov 6,
          2014 &nbsp;&nbsp;<i class="fa fa-comment"></i> 13
        </li>
      </ul>

      <ul class="news">
        <li class="left"><a href="#"><img src="<%= image_path("home/act2.jpg") %>" alt=""/></a></li>
        <li><h5><a href="#">Cuộc thi tên lửa nước</a></h5> <i class="fa fa-clock-o"></i> Nov 12,
          2014 &nbsp;&nbsp;<i class="fa fa-comment"></i> 13
        </li>
      </ul>

      <ul class="news">
        <li class="left"><a href="#"><img src="<%= image_path("home/act3.jpg") %>" alt=""/></a></li>
        <li><h5><a href="#">Lớp kính thiên văn</a></h5> <i class="fa fa-clock-o"></i> Oct 30,
          2014 &nbsp;&nbsp;<i class="fa fa-comment"></i> 13
        </li>
      </ul>

      <div class="clearfix margin_top3"></div>

      <a href="#" class="readmore_but8">Xem thêm <i class="fa fa-long-arrow-right"></i></a>

    </div>
    <!-- end news -->

    <div class="latestblogs">

      <h2 class="section_title_drakgray left">Nhiệm vụ du hành</h2>

      <ul class="hblogs">
        <li class="image"><img src="<%= @mission.first.images[0].attachment_url %>" alt=""/></li>

        <li class="title"><h2 class="nocaps"><%= link_to "Nhiệm vụ tiếp theo của NASA trên "+ @mission.first.element.name, home_mission_path, :class => "two" %></h2>
          by <a href="#" class="three">NASA</a> in <a href="#" class="three">NASA Science</a></li>
        <li class="text">
          <p><%= @mission.first.description %></p></li>
        <li><br/><%= link_to "Xem thêm ", home_mission_path, :class => "readmore_but8" %></li>
      </ul>

    </div>

  </div>
</div><!-- end features section24 -->

<div class="clearfix"></div>

app/views/home/news.html.erb
<!-- Content
======================================= -->

<div class="page_title2">
  <div class="container">

    <div class="title"><h1>Tin tức</h1></div>

    <div class="pagenation">&nbsp;<a href="index.html">Trang chủ</a> <i>/</i> Tin tức</div>

  </div>
</div><!-- end page title -->

<div class="clearfix"></div>

<div class="features_sec3">
  <div class="container">

    <h2 class="section_title_drakgray"><strong>Tin tức</strong></h2>

    <div class="one_fourth">
      <div class="boxsec">

        <img src="<%= image_path("icon/icon-1.png") %>" alt="" />

        <h3>Nhiệm vụ thăm dò</h3>

        <p>Tìm hiểu các thông tin về nhiệm vụ thăm dò hành tinh, không gian và vũ trụ ...</p>

      </div>
      <%= link_to "Xem thêm", home_mission_path, :class=>"readmore_but2" %>
    </div><!-- end section -->

    <div class="one_fourth">
      <div class="boxsec">

        <img src="<%= image_path("icon/icon-2.png") %>" alt="" />

        <h3>Thiên văn thế giới</h3>

        <p>Tổng hợp các bài viết hay và mới nhất về tin tức thiên văn trên thế giới ...</p>

      </div>
      <%= link_to "Xem thêm", home_astroTg_path, :class=>"readmore_but2" %>
    </div><!-- end section -->

    <div class="one_fourth">
      <div class="boxsec">

        <img src="<%= image_path("icon/icon-3.png") %>" alt="" />

        <h3>Thiên văn Việt Nam</h3>

        <p>Tổng hợp các bài viết hay và mới nhất về tin tức thiên văn tại Việt Nam ...</p>

      </div>
      <%= link_to "Xem thêm", home_astroVn_path, :class=>"readmore_but2" %>
    </div><!-- end section -->

    <div class="one_fourth last">
      <div class="boxsec">

        <img src="<%= image_path("icon/icon-4.png") %>" alt="" />

        <h3>Sự kiện & Hoạt động</h3>

        <p>Liên tục cập nhật những sự kiện và hoạt động đặc sắc, nổi bật về thiên văn học...</p>

      </div>
      <a href="#" class="readmore_but2">Xem thêm</a>
    </div><!-- end section -->

  </div>
</div><!-- end features section3 -->

<div class="clearfix margin_top4"></div>

app/views/images/index.html.erb
<% if !flash[:notice].blank? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>
<br />
<%= link_to "New Resume", new_image_path, class: "btn btn-primary" %>
    <br />
    <br />
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Download Link</th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
      <% @images.each do |image| %>
          <tr>
            <td><%= image.image_path %></td>
            <td><%= link_to "Download Resume", image.attachment_url %></td>
            <td><img src="<%= image.attachment_url%>" width="50px" height="50px" alt="meeting" /></td>
            <td><%= button_to "Delete",  image, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{image.image_path}?" %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

  <!-- Favicon -->
  <link rel="shortcut icon" href="favicon.ico">
  <!-- Include meta tag to ensure proper rendering and touch zooming -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">


  <!-- ######### CSS STYLES ######### -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- responsive devices styles -->


</head>

<body>

<div class="site_wrapper">

<header id="header">

  <!-- Top header bar -->
  <div id="topHeader">

    <div class="wrapper">

      <div class="top_nav">
        <div class="container">

          <div class="left">

            <ul>
              <li><a href="mailto:group8-5c11@gmail.com"><i class="fa fa-envelope"></i> group8-5c11@gmail.com</a></li>
              <li><i class="fa fa-phone-square"></i> +84 123 456 789</li>
            </ul>

          </div>
          <!-- end left links -->

          <div class="right">

            <ul>
              <li class="link"><%= render 'layouts/user_widget' %></li>

              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
              <li><a href="https://github.com/aiw-group8-5c11"><i class="fa fa-github-alt"></i></a></li>
              <li><a href="#"><i class="fa fa-rss"></i></a></li>
            </ul>

          </div>
          <!-- end right social links -->

        </div>
      </div>

    </div>

  </div>
  <!-- end top navigation -->


  <div id="trueHeader">

    <div class="wrapper">

      <div class="container">

        <!-- Logo -->
        <div class="logo"><%= link_to "Trang chủ", home_index_path, :id=> "logo" %></div>

        <!-- Menu -->
        <div class="menu_main">

          <nav class="navbar navbar-default fhmm" role="navigation">
            <div class="navbar-header">
              <button type="button" data-toggle="collapse" data-target="#defaultmenu" class="navbar-toggle">Menu <i class="fa fa-bars tbars"></i></button>
            </div><!-- end navbar-header -->

            <div id="defaultmenu" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="page_cur"><%= link_to "Trang chủ", root_path %></li>
                <li class="page_cur"><%= link_to "Giới thiệu", home_about_path %></li>
                <li class="page_cur"><%= link_to "Tin tức", home_news_path %></li>
                <!-- Mega Menu -->
                <li class="dropdown fhmm-fw"><a href="knowledge.html" data-toggle="dropdown" class="dropdown-toggle">Kiến thức</a>
                  <ul class="dropdown-menu fullwidth">
                    <li class="fhmm-content">
                      <div class="row">
                        <div class="col-sm-4">
                          <br>
                          <img src="<%= image_path("menu-1.jpg") %>" alt="" />
                        </div><!-- end col-4 -->

                        <div class="col-sm-2">
                          <h3 class="title">Hệ mặt trời</h3>
                          <ul>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Mặt trời</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Hành tinh</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Các vệ tinh tự nhiên</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Sao chổi</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Tiểu hành tinh</a></li>
                          </ul>
                        </div>

                        <div class="col-sm-2">
                          <h3 class="title">Thiên hà</h3>
                          <ul>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Dải ngân hà</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Tinh vân & Cụm sao</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Ngoại thiên hà</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Sao, hệ sao và ngoại hành tinh</a></li>
                          </ul>
                        </div>

                        <div class="col-sm-2">
                          <h3 class="title">Câu hỏi</h3>
                          <ul>
                            <li><i class="fa fa-angle-right"></i><%= link_to "Trái Đất & Hệ mặt trời", home_question_path %></li>
                            <li><i class="fa fa-angle-right"></i><%= link_to "Thiên cầu & Các chòm sao", home_question_path %></li>
                            <li><i class="fa fa-angle-right"></i><%= link_to " Sao & Thiên hà", home_question_path %></li>
                            <li><i class="fa fa-angle-right"></i><%= link_to "Vũ trụ, không gian & thời gian", home_question_path %></li>
                          </ul>
                        </div>

                      </div><!-- end row -->

                    </li><!-- fhmm-content -->
                  </ul><!-- dropdown-menu -->
                </li><!-- mega menu -->
                <!-- Mega Menu -->
                <li class="page_cur"><%= link_to "Câu hỏi", home_question_path %>
                <li class="page_cur"><%= link_to "Liên hệ", home_contact_path %>

              </ul><!-- end nav navbar-nav -->

            </div><!-- end #navbar-collapse-1 -->

          </nav>

        </div>

      </div>

    </div>

  </div>

</header>

<div class="clearfix"></div>

<%= yield %>

<div class="footer1">
  <div class="container">

    <div class="one_fourth">

      <ul class="faddress">
        <li><img src="<%= image_path("footer-logo.png") %>" alt="Side Logo"/></li>
        <li><i class="fa fa-map-marker fa-lg"></i>&nbsp; Km 9, đường Nguyễn Trãi,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;quận
          Thanh Xuân, Hà Nội, Việt Nam.
        </li>
        <li><i class="fa fa-phone"></i>&nbsp; (84-4)38544338</li>
        <li><i class="fa fa-print"></i>&nbsp; (84-4)38544550</li>
        <li><a href="mailto:info@yourdomain.com"><i class="fa fa-envelope"></i> hanu@hanu.vn</a></li>
      </ul>

    </div>
    <!-- end address -->

    <div class="one_fourth">
      <div class="qlinks">

        <h3 class="lmb nocaps">Liên kết</h3>

        <ul>
          <li><a href="#"><i class="fa fa-angle-right"></i> Phim ảnh thiên văn</a></li>
          <li><a href="#"><i class="fa fa-angle-right"></i> Tiêu điểm quan sát</a></li>
          <li><a href="#"><i class="fa fa-angle-right"></i> Kinh thiên văn</a></li>
          <li><a href="#"><i class="fa fa-angle-right"></i> Công nghệ vũ trụ</a></li>
          <li><a href="#"><i class="fa fa-angle-right"></i> Tin thiên văn thế giới</a></li>
        </ul>

      </div>
    </div>
    <!-- end links -->

    <div class="one_fourth">
      <div class="frposts">

        <h3 class="lmb nocaps">Bài viết mới</h3>

        <ul>
          <li><a href="#"><i class="fa fa-caret-right"></i> Lỗ đen vũ trụ</a></li>
          <li><a href="#"><i class="fa fa-caret-right"></i> Quan sát mưa sao băng</a></li>
          <li><a href="#"><i class="fa fa-caret-right"></i> Phát hiện vật thể lạ</a></li>
          <li><a href="#"><i class="fa fa-caret-right"></i> Sao chổi tấn công Trái Đất</a></li>
        </ul>

      </div>
    </div>
    <!-- end links -->

    <div class="one_fourth last">
      <div class="ftags">

        <h3 class="nocaps">Thẻ Tags</h3>

        <ul>
          <li><a href="#">Thiên văn</a></li>
          <li><a href="#">Thám hiểm</a></li>
          <li><a href="#">Hành tinh</a></li>
          <li><a href="#">Vũ trụ</a></li>
          <li><a href="#">Nhà du hành</a></li>
          <li><a href="#">Khám phá</a></li>
          <li><a href="#">Tinh vân</a></li>
          <li><a href="#">Dải ngân hà</a></li>
          <li><a href="#">Hệ mặt trời</a></li>
        </ul>

      </div>
    </div>
    <!-- end tags -->

  </div>
</div>
<!-- end footer -->

<div class="clearfix"></div>

<div class="copyright_info">
  <div class="container">

    <div class="one_half">

      Copyright © 2014 Group 8 - 5C11. All rights reserved.<br> <a href="#">Điều Khoản</a> |
      <a href="#">Chính Sách Bảo Mật</a>

    </div>

    <div class="one_half last">

      <ul class="footer_social_links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="https://github.com/aiw-group8-5c11"><i class="fa fa-github-alt"></i></a></li>
        <li><a href="#"><i class="fa fa-rss"></i></a></li>
      </ul>

    </div>

  </div>
</div>
<!-- end copyright info -->


<a href="#" class="scrollup">Scroll</a><!-- end scroll to top of the page-->


</div>

<!-- jquery jcarousel -->
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#mycarouselthree').jcarousel();
    });
</script>

<script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-374977-27']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
</script>

<!-- dropdown menu -->
<script type="text/javascript">
    // Menu drop down effect
    $('.dropdown-toggle').dropdownHover().dropdown();
    $(document).on('click', '.fhmm .dropdown-menu', function(e) {
        e.stopPropagation()
    })
</script>

<script type="text/javascript">
    $(function(){
        $('.myGallery').galleryView();
    });
</script>
</body>
</html>